# Configuration for Repo Lockdown - https://github.com/dessant/repo-lockdown-app
# LibreOffice project uses gerrit as its patch management & review system
_extends: core

pulls:
  comment: >
    Thank you for your contribution. We use GitHub as a read-only mirror. Translations are maintained in weblate, see https://wiki.documentfoundation.org/Translating_LibreOffice for details on how to contribute.
